In [16]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error

In [2]:
train_df=pd.read_csv("/kaggle/input/burnout-datathon-ieeecsmuj/train.csv")
test_df=pd.read_csv("/kaggle/input/burnout-datathon-ieeecsmuj/test.csv")
val_df=pd.read_csv("/kaggle/input/burnout-datathon-ieeecsmuj/val.csv")

In [9]:
print(train_df.shape,test_df.shape,val_df.shape)

(2187493, 45) (546874, 44) (273437, 45)

In [3]:
train_df = pd.concat([train_df, val_df], ignore_index=True)

In [8]:
train_df.head()

,Unique ID,Rider_ID,category_x,Circuit_Length_km,Laps,Grid_Position,Avg_Speed_kmh,Track_Condition,Humidity_%,Tire_Compound_Front,...,air,ground,starts,finishes,with_points,podiums,wins,min_year,max_year,years_active
0,1894944,2659,Moto2,4.874,22,17,264.66,Wet,61,Hard,...,23,35,53,45,41,4,0,2018,2021,4
1,23438,5205,Moto2,3.875,24,7,177.56,Wet,77,Soft,...,12,12,27,27,22,2,1,1975,1983,8
2,939678,7392,Moto3,5.647,25,5,317.74,Dry,87,Soft,...,22,23,45,43,10,0,0,1982,1989,8
3,1196312,7894,Moto3,4.810,19,3,321.82,Wet,43,Soft,...,23,35,192,172,155,16,9,1994,2009,16
4,1033899,6163,MotoGP,5.809,25,21,239.92,Wet,47,Hard,...,22,31,175,146,132,29,17,2011,2021,11

In [4]:
train_df .isna().sum()

Unique ID                               0
Rider_ID                                0
category_x                              0
Circuit_Length_km                       0
Laps                                    0
Grid_Position                           0
Avg_Speed_kmh                           0
Track_Condition                         0
Humidity_%                              0
Tire_Compound_Front                     0
Tire_Compound_Rear                      0
Penalty                            366912
Championship_Points                     0
Championship_Position                   0
Session                                 0
year_x                                  0
sequence                                0
rider                                   0
team                                    0
bike                                    0
position                                0
points                                  0
shortname                               0
circuit_name                            0
rider_name                              0
team_name                               0
bike_name                               0
Lap_Time_Seconds                        0
Corners_per_Lap                         0
Tire_Degradation_Factor_per_Lap         0
Pit_Stop_Duration_Seconds               0
Ambient_Temperature_Celsius             0
Track_Temperature_Celsius               0
weather                                 0
track                                   0
air                                     0
ground                                  0
starts                                  0
finishes                                0
with_points                             0
podiums                                 0
wins                                    0
min_year                                0
max_year                                0
years_active                            0
dtype: int64

In [6]:
train_df=train_df.fillna("Unknown")

In [7]:
train_df.describe()

,Unique ID,Rider_ID,Circuit_Length_km,Laps,Grid_Position,Avg_Speed_kmh,Humidity_%,Championship_Points,Championship_Position,year_x,...,air,ground,starts,finishes,with_points,podiums,wins,min_year,max_year,years_active
count,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,...,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06,2.187493e+06
mean,1.367532e+06,5.509889e+03,4.701481e+00,2.150214e+01,1.150059e+01,2.496257e+02,5.951933e+01,1.744660e+02,1.254924e+01,1.997904e+03,...,2.190228e+01,2.973400e+01,1.011851e+02,8.741540e+01,7.091659e+01,1.398067e+01,7.363214e+00,1.993040e+03,2.002499e+03,9.374637e+00
std,7.892527e+05,2.597049e+03,6.912248e-01,2.293291e+00,6.334293e+00,5.773894e+01,1.733871e+01,1.009523e+02,6.914658e+00,1.708516e+01,...,5.929639e+00,1.162802e+01,8.141085e+01,6.983898e+01,6.682392e+01,2.611985e+01,1.638907e+01,1.683207e+01,1.748067e+01,5.144410e+00
min,0.000000e+00,1.000000e+03,3.500000e+00,1.800000e+01,1.000000e+00,1.500000e+02,3.000000e+01,0.000000e+00,1.000000e+00,1.949000e+03,...,1.200000e+01,1.200000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.949000e+03,1.949000e+03,1.000000e+00
25%,6.841440e+05,3.258000e+03,4.103000e+00,1.900000e+01,6.000000e+00,1.993200e+02,4.400000e+01,8.700000e+01,7.000000e+00,1.987000e+03,...,1.700000e+01,2.100000e+01,3.500000e+01,3.100000e+01,1.700000e+01,0.000000e+00,0.000000e+00,1.983000e+03,1.991000e+03,5.000000e+00
50%,1.367844e+06,5.515000e+03,4.703000e+00,2.200000e+01,1.200000e+01,2.496600e+02,6.000000e+01,1.740000e+02,1.300000e+01,2.001000e+03,...,2.100000e+01,2.900000e+01,8.500000e+01,7.400000e+01,5.300000e+01,4.000000e+00,1.000000e+00,1.996000e+03,2.007000e+03,9.000000e+00
75%,2.050997e+06,7.761000e+03,5.299000e+00,2.400000e+01,1.700000e+01,2.994500e+02,7.500000e+01,2.620000e+02,1.900000e+01,2.012000e+03,...,2.600000e+01,4.000000e+01,1.460000e+02,1.230000e+02,1.060000e+02,1.600000e+01,7.000000e+00,2.006000e+03,2.019000e+03,1.200000e+01
max,2.734366e+06,9.998000e+03,5.900000e+00,2.500000e+01,2.200000e+01,3.500000e+02,8.900000e+01,3.490000e+02,2.400000e+01,2.021000e+03,...,3.600000e+01,5.400000e+01,4.060000e+02,3.730000e+02,3.650000e+02,1.780000e+02,1.180000e+02,2.021000e+03,2.021000e+03,2.600000e+01

In [10]:
train_df.dtypes

Unique ID                            int64
Rider_ID                             int64
category_x                          object
Circuit_Length_km                  float64
Laps                                 int64
Grid_Position                        int64
Avg_Speed_kmh                      float64
Track_Condition                     object
Humidity_%                           int64
Tire_Compound_Front                 object
Tire_Compound_Rear                  object
Penalty                             object
Championship_Points                  int64
Championship_Position                int64
Session                             object
year_x                               int64
sequence                             int64
rider                                int64
team                                 int64
bike                                 int64
position                             int64
points                             float64
shortname                           object
circuit_name                        object
rider_name                          object
team_name                           object
bike_name                           object
Lap_Time_Seconds                   float64
Corners_per_Lap                      int64
Tire_Degradation_Factor_per_Lap    float64
Pit_Stop_Duration_Seconds          float64
Ambient_Temperature_Celsius        float64
Track_Temperature_Celsius          float64
weather                             object
track                               object
air                                  int64
ground                               int64
starts                               int64
finishes                             int64
with_points                          int64
podiums                              int64
wins                                 int64
min_year                             int64
max_year                             int64
years_active                         int64
dtype: object

In [11]:
train_df.nunique()

Unique ID                          2187493
Rider_ID                              8999
category_x                               3
Circuit_Length_km                     2401
Laps                                     8
Grid_Position                           22
Avg_Speed_kmh                        19961
Track_Condition                          2
Humidity_%                              60
Tire_Compound_Front                      3
Tire_Compound_Rear                       3
Penalty                                  6
Championship_Points                    350
Championship_Position                   24
Session                                  7
year_x                                  73
sequence                                19
rider                                 2695
team                                   970
bike                                   301
position                                43
points                                  27
shortname                               53
circuit_name                            70
rider_name                            2695
team_name                              967
bike_name                              301
Lap_Time_Seconds                     30205
Corners_per_Lap                         16
Tire_Degradation_Factor_per_Lap         46
Pit_Stop_Duration_Seconds              301
Ambient_Temperature_Celsius            201
Track_Temperature_Celsius              350
weather                                  5
track                                    2
air                                     14
ground                                  16
starts                                 188
finishes                               174
with_points                            151
podiums                                 62
wins                                    44
min_year                                73
max_year                                73
years_active                            23
dtype: int64

In [12]:
# Select numeric columns
numeric_cols = train_df.select_dtypes(include=['number']).columns

# Compute correlation with target
correlations = train_df[numeric_cols].corr()['Lap_Time_Seconds'].drop('Lap_Time_Seconds').sort_values(ascending=False)

# Display correlations
print("📊 Correlation of numeric features with Lap_Time_Seconds:\n")
print(correlations)

📊 Correlation of numeric features with Lap_Time_Seconds:

Corners_per_Lap                    0.008451
team                               0.006977
bike                               0.006297
position                           0.005425
rider                              0.003295
min_year                           0.003066
year_x                             0.001205
Championship_Points                0.000967
Championship_Position              0.000801
Laps                               0.000705
max_year                           0.000626
Tire_Degradation_Factor_per_Lap    0.000575
Rider_ID                           0.000464
Grid_Position                      0.000402
Humidity_%                         0.000055
Unique ID                         -0.000031
Avg_Speed_kmh                     -0.000364
Circuit_Length_km                 -0.000740
air                               -0.001219
Pit_Stop_Duration_Seconds         -0.001746
sequence                          -0.002290
wins                              -0.003580
ground                            -0.003961
podiums                           -0.004151
Ambient_Temperature_Celsius       -0.004481
Track_Temperature_Celsius         -0.004752
starts                            -0.004919
finishes                          -0.006259
points                            -0.007158
years_active                      -0.007178
with_points                       -0.008232
Name: Lap_Time_Seconds, dtype: float64

# Key Mapping Approach

In [13]:
# Convert key columns to string
key_cols = ['rider','circuit_name', 'year_x',
     'Corners_per_Lap', 'Pit_Stop_Duration_Seconds']

for col in key_cols:
    train_df[col] = train_df[col].astype(str)
    test_df[col] = test_df[col].astype(str)

# Create composite key
train_df['key'] = train_df[key_cols].agg('_'.join, axis=1)
test_df['key'] = test_df[key_cols].agg('_'.join, axis=1)

In [14]:
# Step 1: Compute average Lap_Time_Seconds for each key from train_df
key_to_avg_lap_time = train_df.groupby('key')['Lap_Time_Seconds'].mean()

# Step 2: Map this to test_df based on the key
test_df['calc_lap_time'] = test_df['key'].map(key_to_avg_lap_time)

# Step 3: Count NaN values
num_nan = test_df['calc_lap_time'].isna().sum()

print(f"❌ Number of NaN values in test_df['calc_lap_time']: {num_nan}")

❌ Number of NaN values in test_df['calc_lap_time']: 0

In [17]:
train_df['calc_lap_time'] = train_df['key'].map(key_to_avg_lap_time)

# Step 3: Compute RMSE between predicted and actual
rmse_key_mean = mean_squared_error(train_df['Lap_Time_Seconds'], train_df['calc_lap_time'], squared=False)

# Step 4: Print result
print(f"📏 RMSE using group mean by key in train_df: {rmse_key_mean:.4f} seconds")

📏 RMSE using group mean by key in train_df: 0.0000 seconds

In [18]:
# Step 1: Compute mean Lap_Time_Seconds for each key
key_to_avg_lap_time = train_df.groupby('key')['Lap_Time_Seconds'].mean()

# Step 2: Map to test_df
test_df['Lap_Time_Seconds'] = test_df['key'].map(key_to_avg_lap_time)

# Step 3: Handle missing keys (optional: fill with global mean or median)
global_mean = train_df['Lap_Time_Seconds'].mean()
test_df['Lap_Time_Seconds'] = test_df['Lap_Time_Seconds'].fillna(global_mean)

# Step 4: Create submission DataFrame
submission = test_df[['Unique ID', 'Lap_Time_Seconds']]

# Step 5: Save to CSV
submission.to_csv('submission.csv', index=False)

print("✅ Submission file 'submission.csv' created.")

✅ Submission file 'submission.csv' created.